title: Chima Justice
logo: github_profile.png
description: >
  A data analyst with 2 years’ experience using Microsoft Excel for data automation,
  SQL for data manipulation and interrogation, and Power BI for business intelligence reporting.
theme: jekyll-theme-minimal
