title: Chima Justce
logo: IMG_20251209_195516_684.jpg
description: A data analsyst with 2 years experience using microsoft excel for data automation, structured query language (SQL) for data manipulation and interrogation,
power BI for business intelligent report
theme: jekyll-theme-minimal
