logo: github_profile.png
description: A data analyst with 2 years’ experience using Microsoft excel for data automation, structured query language (SQL) for data manipulation and interrogation, power BI for business intelligent report
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
